/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package samplevp;

import java.text.DecimalFormat;
import java.util.InputMismatchException;


public class App {

    public static void main(String[] args) {
        InterfaceSample sample = new InterfaceSample();
    }
}
